/*
A KBase module: kb_go_express
*/

module kb_go_express {
    /*
        A boolean - 0 for false, 1 for true.
        @range (0,1)
    */
    typedef int boolean;


    /* 
    	Reference
    */
    typedef string obj_ref;

  	
  	/*
        required params:
        workspace_name: Name of the workspace
        Number of permutations: num_permutations

    	optional params:

    */

   typedef structure {
        string workspace_name;
        obj_ref expression_ref;
        obj_ref genome_ref;
        list<string> sample_id1;
        list<mapping<string, string>> sample_n_conditions;
        int num_permutations;
    } GOExpressInput;


    /*
        result_directory: folder path that holds all files generated by run_goexpress_app
        report_name: report name generated by KBaseReport
        report_ref: report reference generated by KBaseReport

    */
    typedef structure{
        string result_directory;
        string report_name;
        string report_ref;
    } GOExpressResult;

    /*
        run_goexpress_app
        ref: https://bioconductor.org/packages/release/bioc/html/GOexpress.html

    */
    funcdef run_goexpress_app (GOExpressInput params)
        returns (GOExpressResult returnVal) authentication required;

};
